### ISSUE TITLE
Code: Fix Code Smells and Improve Documentation

### ISSUE THREAD

**Issue by MikeVezina** [Justgo13/SYSC3110-Risk#12]
1. Make sure you don't have methods that are handling way too much logic, such as RiskGame.processCommand(..). Try breaking methods like these down into sub-methods that handle different parts of the logic.

2. Document your methods and code a bit more. **Especially** the methods such as processCommand(..) which are responsible for large pieces of game logic!

**Comment by Justgo13** [comment]
The process command method is now removed and better documentation has been written for milestone 2
