### ISSUE TITLE
Process: GitHub Contributions

### ISSUE THREAD

**Issue by MikeVezina** [Justgo13/SYSC3110-Risk#13]
- Please make sure everyone commits and pushes their own code to GitHub (and that you don't rely on other members to commit code for you). This helps me make sure that everyone is contributing evenly and that everything is fair! You will be deducted marks in the next Milestone if the repository shows you did not commit much (regardless of if someone else submitted code on your behalf!).

- This is also important because I need to see that everyone knows how to use GitHub properly (which is a learning objective of the project)

**Comment by Justgo13** [comment]
This time around work was better distributed among the group members for milestone 2. With group members each contributing a few hundred additions and deletions.
